-- ============================================================
-- 04_GOLD_MODEL.sql
-- VAHAN Regional Vehicle Market Intelligence Platform
-- ============================================================

USE DATABASE VAHAN_MARKET_DB;
USE SCHEMA MARKET_SCHEMA;
USE WAREHOUSE VAHAN_WH;

CREATE OR REPLACE TABLE DIM_DATE AS
SELECT DISTINCT
    DATE AS DATE_KEY,
    YEAR,
    MONTH,
    MONTH_NAME,
    PERIOD
FROM SILVER_VAHAN_VEHICLE_MARKET
WHERE DATE IS NOT NULL;

CREATE OR REPLACE TABLE DIM_STATE AS
SELECT DISTINCT
    STATE_CODE,
    STATE
FROM SILVER_VAHAN_VEHICLE_MARKET
WHERE STATE_CODE IS NOT NULL
  AND STATE IS NOT NULL;

CREATE OR REPLACE TABLE DIM_CATEGORY AS
SELECT DISTINCT
    DIMENSION_VALUE AS CATEGORY_NAME
FROM SILVER_VAHAN_VEHICLE_MARKET
WHERE DATASET_TYPE = 'Vehicle_Category';

CREATE OR REPLACE TABLE DIM_FUEL AS
SELECT DISTINCT
    DIMENSION_VALUE AS FUEL_NAME
FROM SILVER_VAHAN_VEHICLE_MARKET
WHERE DATASET_TYPE = 'Fuel';

CREATE OR REPLACE TABLE DIM_MANUFACTURER AS
SELECT DISTINCT
    DIMENSION_VALUE AS MANUFACTURER_NAME
FROM SILVER_VAHAN_VEHICLE_MARKET
WHERE DATASET_TYPE = 'Manufacturer';

CREATE OR REPLACE TABLE FACT_CATEGORY AS
SELECT
    DATE,
    YEAR,
    MONTH,
    MONTH_NAME,
    PERIOD,
    STATE_CODE,
    STATE,
    DIMENSION_VALUE AS CATEGORY_NAME,
    VEHICLE_COUNT,
    SOURCE_FILE
FROM SILVER_VAHAN_VEHICLE_MARKET
WHERE DATASET_TYPE = 'Vehicle_Category';

CREATE OR REPLACE TABLE FACT_FUEL AS
SELECT
    DATE,
    YEAR,
    MONTH,
    MONTH_NAME,
    PERIOD,
    STATE_CODE,
    STATE,
    DIMENSION_VALUE AS FUEL_NAME,
    VEHICLE_COUNT,
    SOURCE_FILE
FROM SILVER_VAHAN_VEHICLE_MARKET
WHERE DATASET_TYPE = 'Fuel';

CREATE OR REPLACE TABLE FACT_MANUFACTURER AS
SELECT
    DATE,
    YEAR,
    MONTH,
    MONTH_NAME,
    PERIOD,
    STATE_CODE,
    STATE,
    DIMENSION_VALUE AS MANUFACTURER_NAME,
    VEHICLE_COUNT,
    SOURCE_FILE
FROM SILVER_VAHAN_VEHICLE_MARKET
WHERE DATASET_TYPE = 'Manufacturer';

SELECT
    'DIM_DATE' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM DIM_DATE

UNION ALL

SELECT
    'DIM_STATE',
    COUNT(*)
FROM DIM_STATE

UNION ALL

SELECT
    'DIM_CATEGORY',
    COUNT(*)
FROM DIM_CATEGORY

UNION ALL

SELECT
    'DIM_FUEL',
    COUNT(*)
FROM DIM_FUEL

UNION ALL

SELECT
    'DIM_MANUFACTURER',
    COUNT(*)
FROM DIM_MANUFACTURER

UNION ALL

SELECT
    'FACT_CATEGORY',
    COUNT(*)
FROM FACT_CATEGORY

UNION ALL

SELECT
    'FACT_FUEL',
    COUNT(*)
FROM FACT_FUEL

UNION ALL

SELECT
    'FACT_MANUFACTURER',
    COUNT(*)
FROM FACT_MANUFACTURER;

SELECT
    'SILVER' AS SOURCE,
    COUNT(*) AS ROW_COUNT,
    SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM SILVER_VAHAN_VEHICLE_MARKET

UNION ALL

SELECT
    'GOLD' AS SOURCE,
    COUNT(*) AS ROW_COUNT,
    SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM (
    SELECT VEHICLE_COUNT FROM FACT_CATEGORY
    UNION ALL
    SELECT VEHICLE_COUNT FROM FACT_FUEL
    UNION ALL
    SELECT VEHICLE_COUNT FROM FACT_MANUFACTURER
);

SELECT
    DATASET_TYPE,
    COUNT(*) AS SILVER_ROWS,
    SUM(VEHICLE_COUNT) AS SILVER_VEHICLES
FROM SILVER_VAHAN_VEHICLE_MARKET
GROUP BY DATASET_TYPE
ORDER BY DATASET_TYPE;

SELECT
    'FACT_CATEGORY' AS DATASET_TYPE,
    COUNT(*) AS GOLD_ROWS,
    SUM(VEHICLE_COUNT) AS GOLD_VEHICLES
FROM FACT_CATEGORY

UNION ALL

SELECT
    'FACT_FUEL',
    COUNT(*),
    SUM(VEHICLE_COUNT)
FROM FACT_FUEL

UNION ALL

SELECT
    'FACT_MANUFACTURER',
    COUNT(*),
    SUM(VEHICLE_COUNT)
FROM FACT_MANUFACTURER;

SELECT
    'FACT_CATEGORY' AS TABLE_NAME,
    DATE,
    STATE_CODE,
    CATEGORY_NAME,
    COUNT(*) AS DUPLICATE_COUNT
FROM FACT_CATEGORY
GROUP BY DATE, STATE_CODE, CATEGORY_NAME
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'FACT_FUEL',
    DATE,
    STATE_CODE,
    FUEL_NAME,
    COUNT(*)
FROM FACT_FUEL
GROUP BY DATE, STATE_CODE, FUEL_NAME
HAVING COUNT(*) > 1

UNION ALL

SELECT
    'FACT_MANUFACTURER',
    DATE,
    STATE_CODE,
    MANUFACTURER_NAME,
    COUNT(*)
FROM FACT_MANUFACTURER
GROUP BY DATE, STATE_CODE, MANUFACTURER_NAME
HAVING COUNT(*) > 1;

SELECT
    'FACT_CATEGORY' AS TABLE_NAME,
    COUNT_IF(VEHICLE_COUNT IS NULL) AS NULL_COUNTS,
    COUNT_IF(VEHICLE_COUNT < 0) AS NEGATIVE_COUNTS
FROM FACT_CATEGORY

UNION ALL

SELECT
    'FACT_FUEL',
    COUNT_IF(VEHICLE_COUNT IS NULL),
    COUNT_IF(VEHICLE_COUNT < 0)
FROM FACT_FUEL

UNION ALL

SELECT
    'FACT_MANUFACTURER',
    COUNT_IF(VEHICLE_COUNT IS NULL),
    COUNT_IF(VEHICLE_COUNT < 0)
FROM FACT_MANUFACTURER;

SELECT
    'Gold Model Completed Successfully' AS STATUS,
    (SELECT COUNT(*) FROM DIM_DATE) AS DIM_DATE_ROWS,
    (SELECT COUNT(*) FROM DIM_STATE) AS DIM_STATE_ROWS,
    (SELECT COUNT(*) FROM DIM_CATEGORY) AS DIM_CATEGORY_ROWS,
    (SELECT COUNT(*) FROM DIM_FUEL) AS DIM_FUEL_ROWS,
    (SELECT COUNT(*) FROM DIM_MANUFACTURER) AS DIM_MANUFACTURER_ROWS,
    (SELECT COUNT(*) FROM FACT_CATEGORY) AS FACT_CATEGORY_ROWS,
    (SELECT COUNT(*) FROM FACT_FUEL) AS FACT_FUEL_ROWS,
    (SELECT COUNT(*) FROM FACT_MANUFACTURER) AS FACT_MANUFACTURER_ROWS;
