-- ============================================================
-- 05_ANALYTICS_VIEWS.sql
-- VAHAN Vehicle Market Intelligence Platform
-- Purpose: Create reusable Snowflake views
-- ============================================================

USE DATABASE VAHAN_MARKET_DB;
USE SCHEMA MARKET_SCHEMA;
USE WAREHOUSE VAHAN_WH;

CREATE OR REPLACE VIEW VW_CATEGORY_MONTHLY AS
SELECT DATE, YEAR, MONTH, MONTH_NAME, PERIOD,
       STATE_CODE, STATE, CATEGORY_NAME,
       VEHICLE_COUNT, SOURCE_FILE
FROM FACT_CATEGORY;

CREATE OR REPLACE VIEW VW_FUEL_MONTHLY AS
SELECT DATE, YEAR, MONTH, MONTH_NAME, PERIOD,
       STATE_CODE, STATE, FUEL_NAME,
       VEHICLE_COUNT, SOURCE_FILE
FROM FACT_FUEL;

CREATE OR REPLACE VIEW VW_MANUFACTURER_MONTHLY AS
SELECT DATE, YEAR, MONTH, MONTH_NAME, PERIOD,
       STATE_CODE, STATE, MANUFACTURER_NAME,
       VEHICLE_COUNT, SOURCE_FILE
FROM FACT_MANUFACTURER;

CREATE OR REPLACE VIEW VW_CATEGORY_TOTALS AS
SELECT CATEGORY_NAME, SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM FACT_CATEGORY
GROUP BY CATEGORY_NAME;

CREATE OR REPLACE VIEW VW_FUEL_TOTALS AS
SELECT FUEL_NAME, SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM FACT_FUEL
GROUP BY FUEL_NAME;

CREATE OR REPLACE VIEW VW_MANUFACTURER_TOTALS AS
SELECT MANUFACTURER_NAME, SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM FACT_MANUFACTURER
GROUP BY MANUFACTURER_NAME;

CREATE OR REPLACE VIEW VW_STATE_CATEGORY_TOTALS AS
SELECT STATE_CODE, STATE, CATEGORY_NAME,
       SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM FACT_CATEGORY
GROUP BY STATE_CODE, STATE, CATEGORY_NAME;

CREATE OR REPLACE VIEW VW_STATE_FUEL_TOTALS AS
SELECT STATE_CODE, STATE, FUEL_NAME,
       SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM FACT_FUEL
GROUP BY STATE_CODE, STATE, FUEL_NAME;

CREATE OR REPLACE VIEW VW_STATE_MANUFACTURER_TOTALS AS
SELECT STATE_CODE, STATE, MANUFACTURER_NAME,
       SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM FACT_MANUFACTURER
GROUP BY STATE_CODE, STATE, MANUFACTURER_NAME;

CREATE OR REPLACE VIEW VW_STATE_MARKET_SUMMARY AS
SELECT
    COALESCE(C.STATE_CODE, F.STATE_CODE, M.STATE_CODE) AS STATE_CODE,
    COALESCE(C.STATE, F.STATE, M.STATE) AS STATE,
    COALESCE(C.CATEGORY_VEHICLES, 0) AS CATEGORY_VEHICLES,
    COALESCE(F.FUEL_VEHICLES, 0) AS FUEL_VEHICLES,
    COALESCE(M.MANUFACTURER_VEHICLES, 0) AS MANUFACTURER_VEHICLES
FROM (
    SELECT STATE_CODE, STATE, SUM(VEHICLE_COUNT) AS CATEGORY_VEHICLES
    FROM FACT_CATEGORY
    GROUP BY STATE_CODE, STATE
) C
FULL OUTER JOIN (
    SELECT STATE_CODE, STATE, SUM(VEHICLE_COUNT) AS FUEL_VEHICLES
    FROM FACT_FUEL
    GROUP BY STATE_CODE, STATE
) F
ON C.STATE_CODE = F.STATE_CODE
FULL OUTER JOIN (
    SELECT STATE_CODE, STATE, SUM(VEHICLE_COUNT) AS MANUFACTURER_VEHICLES
    FROM FACT_MANUFACTURER
    GROUP BY STATE_CODE, STATE
) M
ON COALESCE(C.STATE_CODE, F.STATE_CODE) = M.STATE_CODE;

CREATE OR REPLACE VIEW VW_CATEGORY_GROWTH AS
WITH BASE AS (
    SELECT *,
           LAG(VEHICLE_COUNT) OVER (
               PARTITION BY STATE_CODE, CATEGORY_NAME
               ORDER BY DATE
           ) AS PREVIOUS_MONTH_VEHICLES
    FROM FACT_CATEGORY
)
SELECT *,
       VEHICLE_COUNT - PREVIOUS_MONTH_VEHICLES AS MONTHLY_CHANGE,
       ROUND(
           (VEHICLE_COUNT - PREVIOUS_MONTH_VEHICLES)
           / NULLIF(PREVIOUS_MONTH_VEHICLES, 0) * 100, 2
       ) AS MONTHLY_GROWTH_PERCENT
FROM BASE;

CREATE OR REPLACE VIEW VW_FUEL_GROWTH AS
WITH BASE AS (
    SELECT *,
           LAG(VEHICLE_COUNT) OVER (
               PARTITION BY STATE_CODE, FUEL_NAME
               ORDER BY DATE
           ) AS PREVIOUS_MONTH_VEHICLES
    FROM FACT_FUEL
)
SELECT *,
       VEHICLE_COUNT - PREVIOUS_MONTH_VEHICLES AS MONTHLY_CHANGE,
       ROUND(
           (VEHICLE_COUNT - PREVIOUS_MONTH_VEHICLES)
           / NULLIF(PREVIOUS_MONTH_VEHICLES, 0) * 100, 2
       ) AS MONTHLY_GROWTH_PERCENT
FROM BASE;

CREATE OR REPLACE VIEW VW_MANUFACTURER_GROWTH AS
WITH BASE AS (
    SELECT *,
           LAG(VEHICLE_COUNT) OVER (
               PARTITION BY STATE_CODE, MANUFACTURER_NAME
               ORDER BY DATE
           ) AS PREVIOUS_MONTH_VEHICLES
    FROM FACT_MANUFACTURER
)
SELECT *,
       VEHICLE_COUNT - PREVIOUS_MONTH_VEHICLES AS MONTHLY_CHANGE,
       ROUND(
           (VEHICLE_COUNT - PREVIOUS_MONTH_VEHICLES)
           / NULLIF(PREVIOUS_MONTH_VEHICLES, 0) * 100, 2
       ) AS MONTHLY_GROWTH_PERCENT
FROM BASE;

CREATE OR REPLACE VIEW VW_TOP_CATEGORY_BY_STATE AS
SELECT *,
       ROW_NUMBER() OVER (
           PARTITION BY STATE_CODE
           ORDER BY TOTAL_VEHICLES DESC
       ) AS CATEGORY_RANK
FROM VW_STATE_CATEGORY_TOTALS;

CREATE OR REPLACE VIEW VW_TOP_FUEL_BY_STATE AS
SELECT *,
       ROW_NUMBER() OVER (
           PARTITION BY STATE_CODE
           ORDER BY TOTAL_VEHICLES DESC
       ) AS FUEL_RANK
FROM VW_STATE_FUEL_TOTALS;

CREATE OR REPLACE VIEW VW_TOP_MANUFACTURER_BY_STATE AS
SELECT *,
       ROW_NUMBER() OVER (
           PARTITION BY STATE_CODE
           ORDER BY TOTAL_VEHICLES DESC
       ) AS MANUFACTURER_RANK
FROM VW_STATE_MANUFACTURER_TOTALS;

CREATE OR REPLACE VIEW VW_CATEGORY_YEARLY AS
SELECT YEAR, STATE_CODE, STATE, CATEGORY_NAME,
       SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM FACT_CATEGORY
GROUP BY YEAR, STATE_CODE, STATE, CATEGORY_NAME;

CREATE OR REPLACE VIEW VW_FUEL_YEARLY AS
SELECT YEAR, STATE_CODE, STATE, FUEL_NAME,
       SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM FACT_FUEL
GROUP BY YEAR, STATE_CODE, STATE, FUEL_NAME;

CREATE OR REPLACE VIEW VW_MANUFACTURER_YEARLY AS
SELECT YEAR, STATE_CODE, STATE, MANUFACTURER_NAME,
       SUM(VEHICLE_COUNT) AS TOTAL_VEHICLES
FROM FACT_MANUFACTURER
GROUP BY YEAR, STATE_CODE, STATE, MANUFACTURER_NAME;

SHOW VIEWS IN SCHEMA VAHAN_MARKET_DB.MARKET_SCHEMA;

SELECT COUNT(*) AS TOTAL_VIEWS
FROM VAHAN_MARKET_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'MARKET_SCHEMA';

SELECT COUNT(*) AS EXPECTED_ANALYTICS_VIEWS
FROM VAHAN_MARKET_DB.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'MARKET_SCHEMA'
  AND TABLE_NAME IN (
      'VW_CATEGORY_MONTHLY',
      'VW_FUEL_MONTHLY',
      'VW_MANUFACTURER_MONTHLY',
      'VW_CATEGORY_TOTALS',
      'VW_FUEL_TOTALS',
      'VW_MANUFACTURER_TOTALS',
      'VW_STATE_CATEGORY_TOTALS',
      'VW_STATE_FUEL_TOTALS',
      'VW_STATE_MANUFACTURER_TOTALS',
      'VW_STATE_MARKET_SUMMARY',
      'VW_CATEGORY_GROWTH',
      'VW_FUEL_GROWTH',
      'VW_MANUFACTURER_GROWTH',
      'VW_TOP_CATEGORY_BY_STATE',
      'VW_TOP_FUEL_BY_STATE',
      'VW_TOP_MANUFACTURER_BY_STATE',
      'VW_CATEGORY_YEARLY',
      'VW_FUEL_YEARLY',
      'VW_MANUFACTURER_YEARLY'
  );
